In [1]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
import pandas as pd
data=pd.read_csv(r"C:\Users\Nithyashakthi\Downloads\Indian Airlines.csv")
data

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...
300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

Intitial Analysis

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
dtypes: float64(1), int64(2), object(8)
memory usage: 25.2+ MB

In [4]:
data.isna().sum()

airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [5]:
data.drop(columns=['flight'], inplace=True)

In [6]:
data

,airline,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...
300148,Vistara,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,Vistara,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,Vistara,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,Vistara,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,Vistara,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [7]:
data.columns

Index(['airline', 'source_city', 'departure_time', 'stops', 'arrival_time',
       'destination_city', 'class', 'duration', 'days_left', 'price'],
      dtype='object')

In [8]:
# Separate numerical and categorical columns
num_cols = ['duration', 'days_left']
cat_cols = ['airline', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class']

In [9]:
# One-Hot Encoding for categorical variables
data = pd.get_dummies(data, columns=cat_cols)

In [10]:
data

,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,source_city_Bangalore,...,arrival_time_Morning,arrival_time_Night,destination_city_Bangalore,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_Business,class_Economy
0,2.17,1,5953,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,True,False,True
1,2.33,1,5953,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,True,False,True
2,2.17,1,5956,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
3,2.25,1,5955,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,True
4,2.33,1,5955,False,False,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,10.08,49,69265,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
300149,10.42,49,77105,False,False,False,False,False,True,False,...,False,True,False,False,False,True,False,False,True,False
300150,13.83,49,79099,False,False,False,False,False,True,False,...,False,True,False,False,False,True,False,False,True,False
300151,10.00,49,81585,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
300152,10.08,49,81585,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False

In [11]:
data.columns

Index(['duration', 'days_left', 'price', 'airline_AirAsia',
       'airline_Air_India', 'airline_GO_FIRST', 'airline_Indigo',
       'airline_SpiceJet', 'airline_Vistara', 'source_city_Bangalore',
       'source_city_Chennai', 'source_city_Delhi', 'source_city_Hyderabad',
       'source_city_Kolkata', 'source_city_Mumbai', 'departure_time_Afternoon',
       'departure_time_Early_Morning', 'departure_time_Evening',
       'departure_time_Late_Night', 'departure_time_Morning',
       'departure_time_Night', 'stops_one', 'stops_two_or_more', 'stops_zero',
       'arrival_time_Afternoon', 'arrival_time_Early_Morning',
       'arrival_time_Evening', 'arrival_time_Late_Night',
       'arrival_time_Morning', 'arrival_time_Night',
       'destination_city_Bangalore', 'destination_city_Chennai',
       'destination_city_Delhi', 'destination_city_Hyderabad',
       'destination_city_Kolkata', 'destination_city_Mumbai', 'class_Business',
       'class_Economy'],
      dtype='object')

In [12]:
# Features & Target
X = data.drop(columns=['price'])
y = data['price']

In [13]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
# Standardize numerical features
scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [15]:
scaler

StandardScaler()

In [16]:
# Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
print('MAE :',mean_absolute_error(y_test, y_pred_lr))
print('MSE :',mean_squared_error(y_test, y_pred_lr))
print('RMSE :',mean_squared_error(y_test, y_pred_lr))
print('R2 Score :',r2_score(y_test, y_pred_lr))

MAE : 4553.231813562992
MSE : 45720668.71063284
RMSE : 45720668.71063284
R2 Score : 0.911305061192324

In [17]:
# Ridge Regression
ridge = Ridge()
ridge.fit(X_train, y_train)
y_pred_ridge = ridge.predict(X_test)
print('MAE:',mean_absolute_error(y_test, y_pred_ridge),
    'MSE:',mean_squared_error(y_test, y_pred_ridge),
    'RMSE:',np.sqrt(mean_squared_error(y_test, y_pred_ridge)),
    'R2 Score:',r2_score(y_test, y_pred_ridge)
     )

MAE: 4553.273074221265 MSE: 45720762.53001751 RMSE: 6761.712987846904 R2 Score: 0.9113048791891991

In [18]:
# Lasso Regression
lasso = Lasso()
lasso.fit(X_train, y_train)
y_pred_lasso = lasso.predict(X_test)
print('MAE:', mean_absolute_error(y_test, y_pred_lasso),
    'MSE:', mean_squared_error(y_test, y_pred_lasso),
    'RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_lasso)),
    'R2 Score:', r2_score(y_test, y_pred_lasso)
     )

MAE: 4551.576783338778 MSE: 45721932.65441484 RMSE: 6761.799513030155 R2 Score: 0.9113026092287032

In [19]:
# Decision Tree
dt = DecisionTreeRegressor()
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
print(
    'MAE:', mean_absolute_error(y_test, y_pred_dt),
    'MSE:', mean_squared_error(y_test, y_pred_dt),
    'RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_dt)),
    'R2 Score:', r2_score(y_test, y_pred_dt)
    )

MAE: 1167.993092457786 MSE: 12569854.003902614 RMSE: 3545.398990791109 R2 Score: 0.975615351587404

In [20]:
# Random Forest
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print(
    'MAE:', mean_absolute_error(y_test, y_pred_rf),
    'MSE:', mean_squared_error(y_test, y_pred_rf),
    'RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_rf)),
    'R2 Score:', r2_score(y_test, y_pred_rf)
    )

MAE: 1078.0564384828963 MSE: 7771622.320276857 RMSE: 2787.762959843763 R2 Score: 0.9849235895805474

In [21]:
# Gradient Boosting
gb = GradientBoostingRegressor()
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)
print(
    'MAE:', mean_absolute_error(y_test, y_pred_gb),
    'MSE:',mean_squared_error(y_test, y_pred_gb),
    'RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_gb)),
    'R2 Score:', r2_score(y_test, y_pred_gb)
)

MAE: 2947.8848258501275 MSE: 24980177.453878418 RMSE: 4998.017352298651 R2 Score: 0.9515401814286814

# SVR
svr = SVR()
svr.fit(X_train, y_train)
y_pred_svr = svr.predict(X_test)
print(
    'MAE:', mean_absolute_error(y_test, y_pred_svr),
    'MSE:',mean_squared_error(y_test, y_pred_svr),
    'RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_svr)),
    'R2 Score:', r2_score(y_test, y_pred_svr)
)

# XGBoost
xgb = XGBRegressor()
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)
print(
    'MAE:', mean_absolute_error(y_test, y_pred_xgb),
    'MSE:', mean_squared_error(y_test, y_pred_xgb),
    'RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_xgb)),
    'R2 Score:', r2_score(y_test, y_pred_xgb)
    )

In [22]:
model_file= open("model.pkl","wb")
pickle.dump(rf, model_file)
scaler_file = open("scaler.pkl","wb")
pickle.dump(scaler, scaler_file)
model_file.close()
scaler_file.close()